### PR TITLE
Change /usr/bin/python to /usr/bin/python3 Fixes #190

### LINKED ISSUE #190: Python interpreter on macOS 12.3
Apple will finally drop python 2 in macOS 12.3. It's already missing in the current beta. Unfortunately, there is no binary `/usr/bin/python` but only `/usr/bin/python3`. Therefore this workflows fails although being python3 compatible (since #111). However, manually correcting the python path in the first line (hash-bang) works for me.

### PR DESCRIPTION
**Pull request by juandesant**
Change of interpreter to /usr/bin/python3 to avoid issues with macOS 12.3 and later.

### CODE REVIEW

**Review by juandesant — COMMENTED** [review]
This Pull Request fixes the interpreter used by the LaTeX bundle. I have tested it on macOS 12.3 with TextMate 2.0.23, and it works perfectly.

**Comment by juandesant** [comment]
I've created a Pull Request above that does all relevant fixes; if it were to be approved, problem would be solved for everyone.

**Comment by sanssecours** [comment]
Thank you for providing a solution for the [recent problems of the Python code in the Bundle](https://github.com/textmate/latex.tmbundle/issues/190) 🙏. For now, I think I will close this in favor of the changes of commit https://github.com/textmate/latex.tmbundle/commit/54d6709ba450d341e0f3d01c930f900c115f8ba8. While the code in this pull request should improve the situation in macOS 12.3 and later, it would most probably make the situation worse for people who use an earlier version of macOS.

In earlier versions of macOS `/usr/bin/python3` seems to also [exist and point to a “stub” that downloads Python3](https://apple.stackexchange.com/questions/376077/is-usr-bin-python3-provided-with-macos-catalina), just like it does now. I mistakenly thought `/usr/bin/python3` does not exist in earlier versions of the OS first. However, as I see it `/usr/bin/python` has two advantages over `/usr/bin/python3`:

- No need to download the intepreter, if you have not done so already.
- The intepreter `/usr/bin/python3` does not ship with [PyObjc](https://pyobjc.readthedocs.io). Unfortunately some Commands of the Bundle depend on this library.

**Comment by juandesant** [comment]
Thanks, @sanssecours for having looked at this, and having provided an alternative way of fixing #190 instead…

Also, in general, many thanks for providing a very useful resource for everyone using TextMate and LaTeX on our Macs… is there a Patreon of Koffi I could contribute to?

**Comment by sanssecours** [comment]
Thank you for your kind words 💖.

> is there a Patreon of Koffi I could contribute to?

I do not think so. I added a PayPal button to the readme a long time ago once, but removed it after some time. I already feel bad about not doing enough work here. At least in the current situation I can honestly state that I work on this Bundle in my free time without any payment 😅.

**Comment by juandesant** [comment]
Having some kind words to someone that out of his kindness gives his time to benefit many people It is the least a decent person can do, really… it is a bit sad that the bar is so low, but then let's try to jump it a bit more often 😉

In any case, yes, I think the personal freedom that that state guarantees you is worth keeping… all the best!

**Pull request closed without merging**
